name: yasin portfolio deploy
on:
  workflow_run:               # this is for triggering the workflow after the validate html workflow is completed
    workflows: [validate html]
    types:
      - completed
  # workflow_dispatch:        // this is for manual trigger of the workflow
  # push:                     // this is for automatic trigger of the workflow on push to master branch
  #   branches:
  #     - master
jobs:
  validat-html-file:
    runs-on: ubuntu-latest
    steps:
      - name: load code
        uses: actions/checkout@v4

      - name: validate html file if exist
        run: test -f index.html
  
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # this is for checking if the validate html workflow is successful
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: run ESlint in app
        run: npm run lint

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
