name: yasin portfolio deploy
on:
  workflow_run:               # this is for triggering the workflow after the validate html workflow is completed
    workflows: [validate html]
    types:
      - completed
  # workflow_dispatch:        // this is for manual trigger of the workflow
  # push:                     // this is for automatic trigger of the workflow on push to master branch
  #   branches:
  #     - master
jobs:
  ESlint-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: run ESlint in app
        run: npm run lint

  run-test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: run all test cases
        run: npm run test

  build-job:
    needs: [ESlint-job, run-test-job]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
  
  artifacts-download-job:
    needs: [ESlint-job, run-test-job, build-job]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Upload artifacts              # this is for uploading the build artifacts to be used in the deploy job
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

  deploy-gh-pages-job:
    needs: [artifacts-download-job]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # this is for checking if the validate html workflow is successful
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist